bigsurvey/main/urls.py
from django.conf.urls import patterns, include, url, static
from django.views.generic import TemplateView
from webapp.admin import admin_site_bigsurvey
from django.conf import settings
from ajax_select import urls as ajax_select_urls
from webapp.forms import EmailValidationOnForgotPassword

urlpatterns = patterns(
    '',
    url(r'^ajax_select/', include(ajax_select_urls)),
    url(r'^admin/', include(admin_site_bigsurvey.urls)),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^', include('webapp.urls', namespace='webapp')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^password/reset/$', 'django.contrib.auth.views.password_reset',
        {'post_reset_redirect': 'done/',
         'password_reset_form': EmailValidationOnForgotPassword}, name="password_reset"),
    url(r'^password/reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(r'^password/reset/complete$', 'django.contrib.auth.views.password_reset_complete',
        name="password_reset_complete"),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        {'post_reset_redirect': 'password_reset_complete'}, name='password_reset_activation'),
    (r'^404/$', TemplateView.as_view(template_name="404.html")),
) + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bigsurvey/webapp/urls.py
from auditlog.views import AuditLogView
from django.conf.urls import patterns, url
from forms import PasswordChangeWithMinLengthForm
from webapp import views

urlpatterns = patterns(
    '',
    url(r'^$', views.HomeView.as_view(), name="home"),
    url(r'^tester-home/$', views.TesterHomeView.as_view(), name="tester-home"),
    url(r'^site/add/$', views.SiteAddView.as_view(), name="site_add"),
    url(r'^site/(?P<pk>\d+)/$', views.SiteDetailView.as_view(), name="site_detail"),
    url(r'^site/(?P<pk>\d+)/edit/$', views.SiteEditView.as_view(), name="site_edit"),
    url(r'^site/(?P<pk>\d+)/add-letter/$', views.LetterAddView.as_view(), name="letter_add"),
    url(r'^site/(?P<pk>\d+)/(?P<service>[a-z]+)/add-survey/$', views.SurveyAddView.as_view(), name="survey_add"),

    url(r'^batch_update/$', views.BatchUpdateView.as_view(), name='batch_update'),

    url(r'^survey/$', views.SurveyListView.as_view(), name="survey_list"),
    url(r'^survey/(?P<pk>\d+)/$', views.SurveyDetailView.as_view(), name="survey_detail"),
    url(r'^survey/(?P<pk>\d+)/edit/$', views.SurveyEditView.as_view(), name="survey_edit"),

    url(r'^hazard/$', views.HazardListView.as_view(), name="hazard_list"),
    url(r'^hazard/(?P<pk>\d+)/$', views.HazardDetailView.as_view(), name="hazard_detail"),
    url(r'^hazard/(?P<pk>\d+)/edit/$', views.HazardEditView.as_view(), name="hazard_edit"),

    url(r'^test/$', views.TestListView.as_view(), name="test_list"),
    url(r'^test/(?P<pk>\d+)/$', views.TestDetailView.as_view(), name="test_detail"),
    url(r'^unsaved-tests/$', views.UnpaidTestView.as_view(), name="unpaid_test_list"),
    url(r'^test/(?P<pk>\d+)/edit/$', views.TestEditView.as_view(), name="test_edit"),
    url(r'^test/pay/paypal/$', views.TestPayPaypalView.as_view(), name="test_pay_paypal"),
    url(r'^testers/$', views.TesterListView.as_view(), name="tester_list"),
    url(r'^user-search/$', views.UserSearchView.as_view(), name="user_search"),
    url(r'^invite-accept/$', views.UserInviteAcceptView.as_view(), name="invite_accept"),

    url(r'^letter_type/$', views.LetterTypeListView.as_view(), name="letter_type_list"),
    url(r'^letter_type/(?P<pk>\d+)/edit/$', views.LetterTypeEditView.as_view(), name="letter_type_edit"),

    url(r'^letter/$', views.LetterListView.as_view(), name="letter_list"),
    url(r'^letter/(?P<pk>\d+)/$', views.LetterDetailView.as_view(), name="letter_detail"),
    url(r'^letter/(?P<pk>\d+)/edit/$', views.LetterEditView.as_view(), name="letter_edit"),
    url(r'^letter/(?P<pk>\d+)/pdf/$', views.LetterPDFView.as_view(), name="letter_pdf"),

    url(r'^pws/$', views.PWSListView.as_view(), name="pws_list"),
    url(r'^pws/(?P<pk>\d+)/$', views.PWSDetailView.as_view(), name="pws_detail"),
    url(r'^pws/add/$', views.PWSAddView.as_view(), name="pws_add"),
    url(r'^pws/(?P<pk>\d+)/edit/$', views.PWSEditView.as_view(), name="pws_edit"),
    url(r'^pws/(?P<pk>\d+)/snapshot/$', views.SnapshotView.as_view(), name="pws_snapshot"),

    url(r'^user/$', views.UserListView.as_view(), name="user_list"),
    url(r'^user/add/$', views.UserAddView.as_view(), name="user_add"),
    url(r'^user/(?P<pk>\d+)/$', views.UserDetailView.as_view(), name="user_detail"),
    url(r'^user/(?P<pk>\d+)/edit/$', views.UserEditView.as_view(), name="user_edit"),

    url(r'^import/$', views.ImportView.as_view(), name="import"),
    url(r'^import-mappings/$', views.ImportMappingsRenderView.as_view(), name="import-mappings"),
    url(r'^import-mappings-process/$', views.ImportMappingsProcessView.as_view(), name="import-mappings-process"),
    url(r'^import-progress/$', views.ImportProgressView.as_view(), name="import-progress"),

    url(r'^import-log/$', views.ImportLogListView.as_view(), name="import_log_list"),
    url(r'^import-log/(?P<pk>\d+)/added/$', views.ImportLogAddedSitesView.as_view(), name="import_log_added_sites"),
    url(r'^import-log/(?P<pk>\d+)/updated/$', views.ImportLogUpdatedSitesView.as_view(), name="import_log_updated_sites"),
    url(r'^import-log/(?P<pk>\d+)/deactivated/$', views.ImportLogDeactivatedSitesView.as_view(), name="import_log_deactivated_sites"),

    url(r'^help/$', views.HelpView.as_view(), name="help"),
    url(r'^get_test_kits/(?P<tester_id>\d+)/', views.get_test_kits, name='get_kits'),
    url(r'^get_tester_certs/(?P<tester_id>\d+)/', views.get_tester_certs, name='get_certs'),

    url(r'^user/(?P<pk>\d+)/cert-add/$', views.TesterCertAddView.as_view(), name="tester_cert_add"),
    url(r'^cert-edit/(?P<pk>\d+)/$', views.TesterCertEditView.as_view(), name="tester_cert_edit"),

    url(r'^user/(?P<pk>\d+)/kit-add/$', views.TestKitAddView.as_view(), name="test_kit_add"),
    url(r'^kit-edit/(?P<pk>\d+)/$', views.TestKitEditView.as_view(), name="test_kit_edit"),

    url(r'^test/(?P<pk>\d+)/pdf/$', views.SingleTestPDFView.as_view(), name="test_pdf"),
    url(r'^password/$', 'django.contrib.auth.views.password_change',
        {'post_change_redirect': '/password/edit/',
         'password_change_form': PasswordChangeWithMinLengthForm},
        name='password'),
    url(r'^audit-log/', AuditLogView.as_view(), name='audit_log'),

    url(r'^hazard/(?P<pk>\d+)/install-bp/$', views.BPDeviceCreateView.as_view(), name="bp_device_add"),
    url(r'^bp-device/(?P<pk>\d+)/edit/$', views.BPDeviceUpdateView.as_view(), name="bp_device_edit"),
    url(r'^bp-device/(?P<pk>\d+)/add-test/$', views.TestAddView.as_view(), name="test_add"),
    url(r'^registration', views.PwsOwnerRegistrationView.as_view(), name="pws_owner_registration"),
    url(r'^download-pdf', views.DownloadPublishedQuiz.as_view(), name="download_pdf"),
    url(r'^activate-blocked-pws', views.ActivateBlockedPWS.as_view(), name="activate_blocked_pws"),
    url(r'^demo-trial/pay/paypal/$', views.DemoTrialPayPaypalView.as_view(), name="demo_trial_paypal"),
    url(r'^test-price/$', views.TestPriceSetupView.as_view(), name='test_price'),
    url(r'^backup/', views.BackupPWSOwner.as_view(), name='backup_pws')
)

bigsurvey/webapp/views/backup_pws_owner.py
import os
from subprocess import call
import shutil
from django.conf import settings
from django.core.exceptions import PermissionDenied
from django.forms import ModelChoiceField
from main.parameters import Messages
from webapp import forms, models
from webapp.actions.demo_trial import IsEmployeeInTrialPeriod
from webapp.views import BaseFormView, reverse, HttpResponseRedirect
from django.contrib import messages


class BackupPWSOwner(BaseFormView):
    success_message = Messages.PWS.backup_success
    permission = 'webapp.browse_backup'
    template_name = 'backup.html'
    form_class = forms.BackupPWSOwnerForm
    model = models.Backup

    def get_context_data(self, **kwargs):
        context = super(BackupPWSOwner, self).get_context_data(**kwargs)
        if not self._user_is_in_demo_trial():
            context['is_demo_trial'] = False
            return context
        raise PermissionDenied

    def get_form(self, form_class):
        form = super(BackupPWSOwner, self).get_form(form_class)
        if self.request.user.has_perm('webapp.access_to_all_sites'):
            form.fields['pws'] = ModelChoiceField(queryset=models.PWS.active_only.all())
        elif self.request.user.has_perm('webapp.browse_backup'):
            form.fields['pws'] = ModelChoiceField(queryset=self.request.user.employee.pws.all())
        return form

    def form_valid(self, form):
        self._deactivate_sites(form)
        python_path = settings.PYTHON_EXECUTABLE
        backup = form.cleaned_data['time_stamp']
        backup_path = backup.file_path
        directory_name = backup.backupbyowner_set.get(pws_owner=self.request.user).directory_name
        number = form.cleaned_data['pws'].number
        call(["/bin/bash", os.path.join(settings.BASE_DIR, "../download_pws_backup.sh"), backup_path])
        call(["/bin/bash", os.path.join(settings.BASE_DIR, "../restore_backup_pws.sh"), python_path, directory_name,
              number])
        shutil.rmtree('/tmp/backup')
        messages.success(self.request, self.success_message)
        return HttpResponseRedirect(self.get_success_url())

    def _deactivate_sites(self, form):
        backup = form.cleaned_data['time_stamp']
        queryset = models.ImportLog.objects.filter(pws__in=self.request.user.employee.pws.all(),
                                                   datetime__gte=backup.time_stamp)
        for import_log in queryset:
            import_log.added_sites.update(status=models.SiteStatus.objects.get(site_status='Inactive'))

    def _user_is_in_demo_trial(self):
        return IsEmployeeInTrialPeriod.check(self.request.user)

    def get_success_url(self):
        return reverse('webapp:backup_pws')

bigsurvey/webapp/views/base_views.py
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import View, FormView, TemplateView, CreateView
from django.contrib import messages
from django.http import Http404, HttpResponseRedirect, HttpResponse
from main.parameters import Messages, TEST_PRICE
from webapp import models
from webapp import forms
from django.utils.translation import ugettext as _


class PermissionRequiredMixin(View):
    permission = None

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        if self.permission and not self.request.user.has_perm(self.permission):
            raise Http404
        return super(PermissionRequiredMixin, self).dispatch(*args, **kwargs)


class BaseView(PermissionRequiredMixin):
    def has_more_link(self):
        user = self.request.user
        return user.has_perm('webapp.access_to_adminpanel') or \
               user.has_perm('webapp.browse_all_pws') or \
               user.has_perm('webapp.browse_lettertype') or \
               not user.is_superuser and user.has_perm('webapp.change_own_pws') and user.employee.pws or \
               user.has_perm('webapp.browse_user') or \
               user.has_perm('webapp.access_to_import') or \
               user.has_perm('webapp.browse_import_log') or \
               user.has_perm('webapp.access_to_batch_update')

    def get_context_data(self, **kwargs):
        context = super(BaseView, self).get_context_data(**kwargs)
        context['has_more_link'] = self.has_more_link()
        return context


class BaseTemplateView(BaseView, TemplateView):
    pass


class BaseFormView(BaseView, FormView):
    success_message = None
    error_message = Messages.form_error

    def form_valid(self, form):
        if self.success_message:
            messages.success(self.request, self.success_message)
        return super(BaseFormView, self).form_valid(form)

    def form_invalid(self, form):
        if self.error_message:
            messages.error(self.request, self.error_message)
        return super(BaseFormView, self).form_invalid(form)


class HelpView(BaseTemplateView):
    template_name = 'help.html'

    def get(self, request, *args, **kwargs):
        if self.request.user.is_superuser:
            return super(HelpView, self).get(request, *args, **kwargs)
        available_help_items = models.StaticText.objects.filter(
            group=self.request.user.groups.all().first(),
            pdf_file__isnull=False
        ).order_by('-pk')
        if available_help_items:
            return HttpResponseRedirect(available_help_items.first().pdf_file.url, content_type='application/pdf')
        return Http404

    def get_context_data(self, **kwargs):
        context = super(HelpView, self).get_context_data(**kwargs)
        help_groups = [(_('Without Group'), models.StaticText.objects.filter(group=None, pdf_file__isnull=False))]
        for group in models.Group.objects.all():
            help_groups.append((group.name, models.StaticText.objects.filter(group=group, pdf_file__isnull=False)))
        context['help_groups'] = help_groups
        return context


class TestPriceSetupView(BaseFormView, CreateView):
    template_name = 'price_setup.html'
    model = models.PriceHistory
    form_class = forms.TestPriceForm
    permission = 'webapp.setup_test_price'
    success_url = reverse_lazy('webapp:test_price')

    def get_context_data(self, **kwargs):
        context = super(TestPriceSetupView, self).get_context_data(**kwargs)
        context['active_prices'] = models.PriceHistory.objects.filter(
                price_type=TEST_PRICE,end_date__isnull=True
            ).order_by('-start_date')
        context['old_prices'] = models.PriceHistory.objects.filter(
            price_type=TEST_PRICE
        ).exclude(end_date__isnull=True).order_by('-start_date')
        return context

    def form_valid(self, form):
        pws_multiple=form.cleaned_data.get('pws_multiple')
        if not pws_multiple:
            form.save_price(pws=None)
        else:
            form.save_multiple()
        return HttpResponseRedirect(self.success_url)

bigsurvey/webapp/views/bp_device_views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponseRedirect
from django.views.generic import CreateView, UpdateView
from .base_views import BaseFormView
from main.parameters import AssemblyStatus, Messages
from webapp.models import BPDevice, Hazard
from webapp.forms import BPForm


class BPDeviceBaseFormView(BaseFormView):
    template_name = "bp_device/bp_device_form.html"
    form_class = BPForm
    model = BPDevice

    def get_context_data(self, **kwargs):
        user = self.request.user
        if user.has_perm("webapp.change_hazard") or user.employee.has_licence_for_installation:
            return super(BPDeviceBaseFormView, self).get_context_data(**kwargs)
        raise Http404

    def get_success_url(self):
        return reverse('webapp:hazard_detail', args=(self.object.hazard.pk,))


class BPDeviceCreateView(BPDeviceBaseFormView, CreateView):
    permission = 'webapp.add_bpdevice'
    success_message = Messages.BPDevice.adding_success

    def form_valid(self, form):
        self.object = form.save()
        self._update_hazard(self.object)
        messages.success(self.request, self.success_message)
        return HttpResponseRedirect(self.get_success_url())

    def _update_hazard(self, bp_device):
        hazard = Hazard.objects.get(pk=self.kwargs['pk'])
        hazard.bp_device = bp_device
        user = self.request.user
        if not user.has_perm('webapp.change_hazard'):
            hazard.assembly_status = AssemblyStatus.INSTALLED
        hazard.save()

    def get_context_data(self, **kwargs):
        context = super(BPDeviceCreateView, self).get_context_data(**kwargs)
        if self.allowed():
            context['hazard_pk'] = self.kwargs['pk']
            return context
        raise Http404

    def allowed(self):
        hazard = Hazard.objects.get(pk=self.kwargs['pk'])
        user = self.request.user
        return user.has_perm('webapp.access_to_all_devices') or\
               hazard.site.pws in user.employee.pws.all() and user.has_perm('webapp.access_to_pws_devices')


class BPDeviceUpdateView(BPDeviceBaseFormView, UpdateView):
    permission = 'webapp.change_bpdevice'
    success_message = Messages.BPDevice.editing_success

    def get_context_data(self, **kwargs):
        context = super(BPDeviceUpdateView, self).get_context_data(**kwargs)
        hazard = context['form'].instance.hazard
        if self.allowed(hazard):
            context['hazard_pk'] = hazard.pk
            return context
        raise Http404

    def allowed(self, hazard):
        user = self.request.user
        return user.has_perm('webapp.access_to_all_devices') or\
               hazard.site.pws in user.employee.pws.all() and user.has_perm('webapp.access_to_pws_devices')

bigsurvey/webapp/views/helpers.py
class OperationNotAllowedInTrialPeriodException(Exception):
    pass

bigsurvey/webapp/templates/pws/activate_blocked_pws.html
{% extends 'base.html' %}
{% load i18n staticfiles %}
{% block content %}
    {% if can_pay %}
        <div class="wrapper uk-width-1-1 uk-text-center">
            {% include 'messages.html' %}
            <button class="uk-button uk-button-primary uk-button-large uk-width-1-3"
                    data-uk-modal="{target: '#modal-paypal'}">
                {% trans "Pay and activate" %}
            </button>
            <div id="modal-paypal" class="uk-modal">
                <div class="uk-modal-dialog">
                    <a class="uk-modal-close uk-close"></a>

                    <div class="uk-modal-spinner hidden spinner-crossbrowser" data-content="spinner"></div>
                    <div class="uk-alert uk-alert-danger hidden" data-content="error-alert" data-uk-alert>
                        <p data-content="error-message"></p>
                    </div>
                    <div data-content="step-1">
                        <h3>{% trans 'Step' %} 1</h3>
                        <a data-content="creation-link"
                           id="payment_creation_link">{% trans 'Click here to proceed to PayPal form' %}</a>
                    </div>
                    <div data-content="step-2" class="hidden">
                        <h3>{% trans 'Step' %} 2</h3>

                        <h3>{% trans 'Total amount:' %} <span class="uk-text-success">$<span
                                data-content="total-amount"></span></span></h3>
                        <a data-content="approval-link" id="approval_link"><img
                                src="{% static 'img/paypal-button.png' %}"></a>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <div class="wrapper uk-width-1-1 uk-text-center">
            <div class="uk-panel uk-panel-box uk-panel-box-primary">
                <div class="uk-panel-badge uk-badge uk-badge-danger">{% trans "Warning!" %}</div>
                <h3 class="uk-panel-title">{% trans "Warning" %}</h3>
                {% blocktrans %}
                    Sorry, your PWS is deactivated. Please, ask your PWS owner for details.
                {% endblocktrans %}
            </div>
        </div>
    {% endif %}
{% endblock %}
{% block scripts %}
    <script src="{% static 'js/custom/demo_trial_paypal.js' %}"></script>
{% endblock %}

bigsurvey/webapp/templates/pws/pws.html
{% extends 'base.html' %}
{% load i18n staticfiles choices %}
{% block menu %}
    <li><a href="{% url 'webapp:pws_snapshot' pws.pk %}" id="pws_{{ pws.pk }}_snapshot_link">{% trans "Snapshot" %}</a>
    </li>
    {% if perms.webapp.change_own_pws %}
        <li><a href="{% url 'webapp:pws_edit' pws.pk %}" id="pws_{{ pws.pk }}_edit_link">{% trans "Edit" %}</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <div class="wrapper">
        {% include 'messages.html' %}
        <table class="uk-table border-none uk-table-condensed">
            <tbody>
            <tr>
                <td class="uk-text-right uk-text-muted">{% trans "Number" %}</td>
                <td class="uk-text-center uk-text-primary">{{ pws.number }}</td>
                <td class="uk-text-right uk-text-muted">{% trans "Name" %}</td>
                <td class="uk-text-center uk-text-primary">{{ pws.name }}</td>
                <td class="uk-text-right uk-text-muted">{% trans "Water Source" %}</td>
                <td class="uk-text-center uk-text-primary">{{ pws.water_source }}</td>
            </tr>
            <tr>
                <td class="uk-text-right uk-text-muted">{% trans "City" %}</td>
                <td class="uk-text-center uk-text-primary">{{ pws.city }}</td>
                <td class="uk-text-right uk-text-muted">{% trans "State" %}</td>
                <td class="uk-text-center uk-text-primary">{{ pws.state }}</td>
                <td class="uk-text-right uk-text-muted">{% trans "Zip" %}</td>
                <td class="uk-text-center uk-text-primary">{{ pws.zip }}</td>
            </tr>
            <tr>
                <td class="uk-text-right uk-text-muted">{% trans "County" %}</td>
                <td class="uk-text-center uk-text-primary">{{ pws.county }}</td>
            </tr>
            <tr>
                <td class="uk-text-right uk-text-muted">{% trans "Office Address" %}</td>
                <td class="uk-text-center uk-text-primary">{{ pws.office_address }}</td>
                <td class="uk-text-right uk-text-muted">{% trans "Phone" %}</td>
                <td class="uk-text-center uk-text-primary">{{ pws.phone }}</td>
                <td class="uk-text-right uk-text-muted">{% trans "Email" %}</td>
                <td class="uk-text-center uk-text-primary">{{ pws.email }}</td>
            </tr>
            <tr class="border-bottom">
                <td class="uk-text-right uk-text-muted">{% trans "Fax" %}</td>
                <td class="uk-text-center uk-text-primary">{{ pws.fax }}</td>
                <td colspan="4"></td>
            </tr>
            <tr>
                <td class="uk-text-right uk-text-muted">{% trans "Person In Charge Name" %}</td>
                <td class="uk-text-center uk-text-primary">{{ pws.bailee_name }}</td>
                <td class="uk-text-right uk-text-muted">{% trans "Person In Charge Job Title" %}</td>
                <td class="uk-text-center uk-text-primary">{{ pws.bailee_job_title }}</td>
                <td class="uk-text-right uk-text-muted">{% trans "Consultant Name" %}</td>
                <td class="uk-text-center uk-text-primary">{{ pws.consultant_name }}</td>
            </tr>
            <tr>
                <td class="uk-text-right uk-text-muted">{% trans "Consultant Phone" %}</td>
                <td class="uk-text-center uk-text-primary">{{ pws.consultant_phone }}</td>
                <td class="uk-text-right uk-text-muted">{% trans "Plumber Packet Location" %}</td>
                <td class="uk-text-center uk-text-primary">{{ pws.plumber_packet_location }}</td>
                <td class="uk-text-right uk-text-muted">{% trans "Plumber Packet Address" %}</td>
                <td class="uk-text-center uk-text-primary">{{ pws.plumber_packet_address }}</td>
            </tr>
            <tr class="border-bottom">
                <td class="uk-text-right uk-text-muted">{% trans "Description" %}</td>
                <td class="uk-text-primary" colspan="5">{{ pws.notes }}</td>
            </tr>
            <tr>
                <td></td>
                <td class="uk-text-right uk-text-muted">{% trans "Logo" %}</td>
                <td class="uk-text-center uk-text-primary" colspan="2">
                    {% if pws.logo %}
                        <img src="{{ pws.logo.url }}" style="max-width: 100%; max-height: 250px;">
                    {% else %}
                        <span>{% trans "No logo available" %}</span>
                    {% endif %}
                </td>
                <td colspan="2"></td>
            </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

bigsurvey/webapp/templates/pws/pws_list.html
{% extends 'base.html' %}
{% load i18n staticfiles common %}
{% block menu %}
    {% if request.user|has_access:'add_pws' %}
    <li><a href="{% url 'webapp:pws_add' %}" id="pws_add_link">{% trans "Add PWS" %}</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <div class="wrapper">
        {% include 'messages.html' %}
        <table class="uk-table">
            <thead>
            <tr class="border-bottom">
                <th class="border-right uk-text-center">{% trans "No." %}</th>
                <th>{% trans "Number" %}</th>
                <th>{% trans "Name" %}</th>
                <th>{% trans "City" %}</th>
                <th>{% trans "Office Address" %}</th>
                <th>{% trans "Water Source" %}</th>
                <th colspan="2" class="uk-text-center border-left">{% trans "Actions" %}</th>
            </tr>
            </thead>
            <tbody>
            {% for pws in pws_list %}
                <tr>
                    <td class="border-right uk-text-center">{{ pws.pk }}</td>
                    <td>{{ pws.number }}</td>
                    <td>{{ pws.name }}</td>
                    <td>{{ pws.city }}</td>
                    <td>{{ pws.office_address }}</td>
                    <td>{{ pws.water_source }}</td>
                    <td class="uk-text-center border-left border-bottom">
                        <a id="pws_{{ pws.pk }}_detail_link" href="{% url 'webapp:pws_detail' pws.pk %}">{% trans "Detail" %}</a>
                    </td>
                    <td class="uk-text-center">
                        <a id="pws_{{ pws.pk }}_snapshot_link" href="{% url 'webapp:pws_snapshot' pws.pk %}">{% trans "Snapshot" %}</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

bigsurvey/webapp/templates/pws/snapshot.html
{% extends "base.html" %}
{% load i18n %}
{% block menu %}
    <li><a href="{% url 'webapp:pws_detail' pws_pk %}" id="pws_{{ pws_pk }}_edit_link">{% trans "PWS Info" %}</a></li>
{% endblock %}
{% block content %}
    <div class="uk-align-center uk-width-large-2-5 uk-width-medium-3-5 uk-width-small-9-10">
        <table class="uk-table">
            {% for item in snapshot_items %}
                <tr>
                    <td class="uk-text-right border-right uk-width-3-5">{% trans item.title %}</td>
                    <td class="uk-text-left">{{ item.value }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}