bigsurvey/main/urls.py
from django.conf.urls import patterns, include, url, static
from django.views.generic import TemplateView
from webapp.admin import admin_site_bigsurvey
from django.conf import settings
from ajax_select import urls as ajax_select_urls
from webapp.forms import EmailValidationOnForgotPassword

urlpatterns = patterns(
    '',
    url(r'^ajax_select/', include(ajax_select_urls)),
    url(r'^admin/', include(admin_site_bigsurvey.urls)),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^', include('webapp.urls', namespace='webapp')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^password/reset/$', 'django.contrib.auth.views.password_reset',
        {'post_reset_redirect': 'done/',
         'password_reset_form': EmailValidationOnForgotPassword}, name="password_reset"),
    url(r'^password/reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(r'^password/reset/complete$', 'django.contrib.auth.views.password_reset_complete',
        name="password_reset_complete"),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        {'post_reset_redirect': 'password_reset_complete'}, name='password_reset_activation'),
    (r'^404/$', TemplateView.as_view(template_name="404.html")),
) + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bigsurvey/webapp/urls.py
from auditlog.views import AuditLogView
from django.conf.urls import patterns, url
from forms import PasswordChangeWithMinLengthForm
from webapp import views

urlpatterns = patterns(
    '',
    url(r'^$', views.HomeView.as_view(), name="home"),
    url(r'^tester-home/$', views.TesterHomeView.as_view(), name="tester-home"),
    url(r'^site/add/$', views.SiteAddView.as_view(), name="site_add"),
    url(r'^site/(?P<pk>\d+)/$', views.SiteDetailView.as_view(), name="site_detail"),
    url(r'^site/(?P<pk>\d+)/edit/$', views.SiteEditView.as_view(), name="site_edit"),
    url(r'^site/(?P<pk>\d+)/add-letter/$', views.LetterAddView.as_view(), name="letter_add"),
    url(r'^site/(?P<pk>\d+)/(?P<service>[a-z]+)/add-survey/$', views.SurveyAddView.as_view(), name="survey_add"),

    url(r'^batch_update/$', views.BatchUpdateView.as_view(), name='batch_update'),

    url(r'^survey/$', views.SurveyListView.as_view(), name="survey_list"),
    url(r'^survey/(?P<pk>\d+)/$', views.SurveyDetailView.as_view(), name="survey_detail"),
    url(r'^survey/(?P<pk>\d+)/edit/$', views.SurveyEditView.as_view(), name="survey_edit"),

    url(r'^hazard/$', views.HazardListView.as_view(), name="hazard_list"),
    url(r'^hazard/(?P<pk>\d+)/$', views.HazardDetailView.as_view(), name="hazard_detail"),
    url(r'^hazard/(?P<pk>\d+)/edit/$', views.HazardEditView.as_view(), name="hazard_edit"),

    url(r'^test/$', views.TestListView.as_view(), name="test_list"),
    url(r'^test/(?P<pk>\d+)/$', views.TestDetailView.as_view(), name="test_detail"),
    url(r'^unsaved-tests/$', views.UnpaidTestView.as_view(), name="unpaid_test_list"),
    url(r'^test/(?P<pk>\d+)/edit/$', views.TestEditView.as_view(), name="test_edit"),
    url(r'^test/pay/paypal/$', views.TestPayPaypalView.as_view(), name="test_pay_paypal"),
    url(r'^testers/$', views.TesterListView.as_view(), name="tester_list"),
    url(r'^user-search/$', views.UserSearchView.as_view(), name="user_search"),
    url(r'^invite-accept/$', views.UserInviteAcceptView.as_view(), name="invite_accept"),

    url(r'^letter_type/$', views.LetterTypeListView.as_view(), name="letter_type_list"),
    url(r'^letter_type/(?P<pk>\d+)/edit/$', views.LetterTypeEditView.as_view(), name="letter_type_edit"),

    url(r'^letter/$', views.LetterListView.as_view(), name="letter_list"),
    url(r'^letter/(?P<pk>\d+)/$', views.LetterDetailView.as_view(), name="letter_detail"),
    url(r'^letter/(?P<pk>\d+)/edit/$', views.LetterEditView.as_view(), name="letter_edit"),
    url(r'^letter/(?P<pk>\d+)/pdf/$', views.LetterPDFView.as_view(), name="letter_pdf"),

    url(r'^pws/$', views.PWSListView.as_view(), name="pws_list"),
    url(r'^pws/(?P<pk>\d+)/$', views.PWSDetailView.as_view(), name="pws_detail"),
    url(r'^pws/add/$', views.PWSAddView.as_view(), name="pws_add"),
    url(r'^pws/(?P<pk>\d+)/edit/$', views.PWSEditView.as_view(), name="pws_edit"),
    url(r'^pws/(?P<pk>\d+)/snapshot/$', views.SnapshotView.as_view(), name="pws_snapshot"),

    url(r'^user/$', views.UserListView.as_view(), name="user_list"),
    url(r'^user/add/$', views.UserAddView.as_view(), name="user_add"),
    url(r'^user/(?P<pk>\d+)/$', views.UserDetailView.as_view(), name="user_detail"),
    url(r'^user/(?P<pk>\d+)/edit/$', views.UserEditView.as_view(), name="user_edit"),

    url(r'^import/$', views.ImportView.as_view(), name="import"),
    url(r'^import-mappings/$', views.ImportMappingsRenderView.as_view(), name="import-mappings"),
    url(r'^import-mappings-process/$', views.ImportMappingsProcessView.as_view(), name="import-mappings-process"),
    url(r'^import-progress/$', views.ImportProgressView.as_view(), name="import-progress"),

    url(r'^import-log/$', views.ImportLogListView.as_view(), name="import_log_list"),
    url(r'^import-log/(?P<pk>\d+)/added/$', views.ImportLogAddedSitesView.as_view(), name="import_log_added_sites"),
    url(r'^import-log/(?P<pk>\d+)/updated/$', views.ImportLogUpdatedSitesView.as_view(), name="import_log_updated_sites"),
    url(r'^import-log/(?P<pk>\d+)/deactivated/$', views.ImportLogDeactivatedSitesView.as_view(), name="import_log_deactivated_sites"),

    url(r'^help/$', views.HelpView.as_view(), name="help"),
    url(r'^get_test_kits/(?P<tester_id>\d+)/', views.get_test_kits, name='get_kits'),
    url(r'^get_tester_certs/(?P<tester_id>\d+)/', views.get_tester_certs, name='get_certs'),

    url(r'^user/(?P<pk>\d+)/cert-add/$', views.TesterCertAddView.as_view(), name="tester_cert_add"),
    url(r'^cert-edit/(?P<pk>\d+)/$', views.TesterCertEditView.as_view(), name="tester_cert_edit"),

    url(r'^user/(?P<pk>\d+)/kit-add/$', views.TestKitAddView.as_view(), name="test_kit_add"),
    url(r'^kit-edit/(?P<pk>\d+)/$', views.TestKitEditView.as_view(), name="test_kit_edit"),

    url(r'^test/(?P<pk>\d+)/pdf/$', views.SingleTestPDFView.as_view(), name="test_pdf"),
    url(r'^password/$', 'django.contrib.auth.views.password_change',
        {'post_change_redirect': '/password/edit/',
         'password_change_form': PasswordChangeWithMinLengthForm},
        name='password'),
    url(r'^audit-log/', AuditLogView.as_view(), name='audit_log'),

    url(r'^hazard/(?P<pk>\d+)/install-bp/$', views.BPDeviceCreateView.as_view(), name="bp_device_add"),
    url(r'^bp-device/(?P<pk>\d+)/edit/$', views.BPDeviceUpdateView.as_view(), name="bp_device_edit"),
    url(r'^bp-device/(?P<pk>\d+)/add-test/$', views.TestAddView.as_view(), name="test_add"),
    url(r'^registration', views.PwsOwnerRegistrationView.as_view(), name="pws_owner_registration"),
    url(r'^download-pdf', views.DownloadPublishedQuiz.as_view(), name="download_pdf"),
    url(r'^activate-blocked-pws', views.ActivateBlockedPWS.as_view(), name="activate_blocked_pws"),
    url(r'^demo-trial/pay/paypal/$', views.DemoTrialPayPaypalView.as_view(), name="demo_trial_paypal"),
    url(r'^test-price/$', views.TestPriceSetupView.as_view(), name='test_price'),
    url(r'^backup/', views.BackupPWSOwner.as_view(), name='backup_pws')
)

bigsurvey/webapp/views/backup_pws_owner.py
import os
from subprocess import call
import shutil
from django.conf import settings
from django.core.exceptions import PermissionDenied
from django.forms import ModelChoiceField
from main.parameters import Messages
from webapp import forms, models
from webapp.actions.demo_trial import IsEmployeeInTrialPeriod
from webapp.views import BaseFormView, reverse, HttpResponseRedirect
from django.contrib import messages


class BackupPWSOwner(BaseFormView):
    success_message = Messages.PWS.backup_success
    permission = 'webapp.browse_backup'
    template_name = 'backup.html'
    form_class = forms.BackupPWSOwnerForm
    model = models.Backup

    def get_context_data(self, **kwargs):
        context = super(BackupPWSOwner, self).get_context_data(**kwargs)
        if not self._user_is_in_demo_trial():
            context['is_demo_trial'] = False
            return context
        raise PermissionDenied

    def get_form(self, form_class):
        form = super(BackupPWSOwner, self).get_form(form_class)
        if self.request.user.has_perm('webapp.access_to_all_sites'):
            form.fields['pws'] = ModelChoiceField(queryset=models.PWS.active_only.all())
        elif self.request.user.has_perm('webapp.browse_backup'):
            form.fields['pws'] = ModelChoiceField(queryset=self.request.user.employee.pws.all())
        return form

    def form_valid(self, form):
        self._deactivate_sites(form)
        python_path = settings.PYTHON_EXECUTABLE
        backup = form.cleaned_data['time_stamp']
        backup_path = backup.file_path
        directory_name = backup.backupbyowner_set.get(pws_owner=self.request.user).directory_name
        number = form.cleaned_data['pws'].number
        call(["/bin/bash", os.path.join(settings.BASE_DIR, "../download_pws_backup.sh"), backup_path])
        call(["/bin/bash", os.path.join(settings.BASE_DIR, "../restore_backup_pws.sh"), python_path, directory_name,
              number])
        shutil.rmtree('/tmp/backup')
        messages.success(self.request, self.success_message)
        return HttpResponseRedirect(self.get_success_url())

    def _deactivate_sites(self, form):
        backup = form.cleaned_data['time_stamp']
        queryset = models.ImportLog.objects.filter(pws__in=self.request.user.employee.pws.all(),
                                                   datetime__gte=backup.time_stamp)
        for import_log in queryset:
            import_log.added_sites.update(status=models.SiteStatus.objects.get(site_status='Inactive'))

    def _user_is_in_demo_trial(self):
        return IsEmployeeInTrialPeriod.check(self.request.user)

    def get_success_url(self):
        return reverse('webapp:backup_pws')

bigsurvey/webapp/views/base_views.py
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import View, FormView, TemplateView, CreateView
from django.contrib import messages
from django.http import Http404, HttpResponseRedirect, HttpResponse
from main.parameters import Messages, TEST_PRICE
from webapp import models
from webapp import forms
from django.utils.translation import ugettext as _


class PermissionRequiredMixin(View):
    permission = None

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        if self.permission and not self.request.user.has_perm(self.permission):
            raise Http404
        return super(PermissionRequiredMixin, self).dispatch(*args, **kwargs)


class BaseView(PermissionRequiredMixin):
    def has_more_link(self):
        user = self.request.user
        return user.has_perm('webapp.access_to_adminpanel') or \
               user.has_perm('webapp.browse_all_pws') or \
               user.has_perm('webapp.browse_lettertype') or \
               not user.is_superuser and user.has_perm('webapp.change_own_pws') and user.employee.pws or \
               user.has_perm('webapp.browse_user') or \
               user.has_perm('webapp.access_to_import') or \
               user.has_perm('webapp.browse_import_log') or \
               user.has_perm('webapp.access_to_batch_update')

    def get_context_data(self, **kwargs):
        context = super(BaseView, self).get_context_data(**kwargs)
        context['has_more_link'] = self.has_more_link()
        return context


class BaseTemplateView(BaseView, TemplateView):
    pass


class BaseFormView(BaseView, FormView):
    success_message = None
    error_message = Messages.form_error

    def form_valid(self, form):
        if self.success_message:
            messages.success(self.request, self.success_message)
        return super(BaseFormView, self).form_valid(form)

    def form_invalid(self, form):
        if self.error_message:
            messages.error(self.request, self.error_message)
        return super(BaseFormView, self).form_invalid(form)


class HelpView(BaseTemplateView):
    template_name = 'help.html'

    def get(self, request, *args, **kwargs):
        if self.request.user.is_superuser:
            return super(HelpView, self).get(request, *args, **kwargs)
        available_help_items = models.StaticText.objects.filter(
            group=self.request.user.groups.all().first(),
            pdf_file__isnull=False
        ).order_by('-pk')
        if available_help_items:
            return HttpResponseRedirect(available_help_items.first().pdf_file.url, content_type='application/pdf')
        return Http404

    def get_context_data(self, **kwargs):
        context = super(HelpView, self).get_context_data(**kwargs)
        help_groups = [(_('Without Group'), models.StaticText.objects.filter(group=None, pdf_file__isnull=False))]
        for group in models.Group.objects.all():
            help_groups.append((group.name, models.StaticText.objects.filter(group=group, pdf_file__isnull=False)))
        context['help_groups'] = help_groups
        return context


class TestPriceSetupView(BaseFormView, CreateView):
    template_name = 'price_setup.html'
    model = models.PriceHistory
    form_class = forms.TestPriceForm
    permission = 'webapp.setup_test_price'
    success_url = reverse_lazy('webapp:test_price')

    def get_context_data(self, **kwargs):
        context = super(TestPriceSetupView, self).get_context_data(**kwargs)
        context['active_prices'] = models.PriceHistory.objects.filter(
                price_type=TEST_PRICE,end_date__isnull=True
            ).order_by('-start_date')
        context['old_prices'] = models.PriceHistory.objects.filter(
            price_type=TEST_PRICE
        ).exclude(end_date__isnull=True).order_by('-start_date')
        return context

    def form_valid(self, form):
        pws_multiple=form.cleaned_data.get('pws_multiple')
        if not pws_multiple:
            form.save_price(pws=None)
        else:
            form.save_multiple()
        return HttpResponseRedirect(self.success_url)

bigsurvey/webapp/views/bp_device_views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponseRedirect
from django.views.generic import CreateView, UpdateView
from .base_views import BaseFormView
from main.parameters import AssemblyStatus, Messages
from webapp.models import BPDevice, Hazard
from webapp.forms import BPForm


class BPDeviceBaseFormView(BaseFormView):
    template_name = "bp_device/bp_device_form.html"
    form_class = BPForm
    model = BPDevice

    def get_context_data(self, **kwargs):
        user = self.request.user
        if user.has_perm("webapp.change_hazard") or user.employee.has_licence_for_installation:
            return super(BPDeviceBaseFormView, self).get_context_data(**kwargs)
        raise Http404

    def get_success_url(self):
        return reverse('webapp:hazard_detail', args=(self.object.hazard.pk,))


class BPDeviceCreateView(BPDeviceBaseFormView, CreateView):
    permission = 'webapp.add_bpdevice'
    success_message = Messages.BPDevice.adding_success

    def form_valid(self, form):
        self.object = form.save()
        self._update_hazard(self.object)
        messages.success(self.request, self.success_message)
        return HttpResponseRedirect(self.get_success_url())

    def _update_hazard(self, bp_device):
        hazard = Hazard.objects.get(pk=self.kwargs['pk'])
        hazard.bp_device = bp_device
        user = self.request.user
        if not user.has_perm('webapp.change_hazard'):
            hazard.assembly_status = AssemblyStatus.INSTALLED
        hazard.save()

    def get_context_data(self, **kwargs):
        context = super(BPDeviceCreateView, self).get_context_data(**kwargs)
        if self.allowed():
            context['hazard_pk'] = self.kwargs['pk']
            return context
        raise Http404

    def allowed(self):
        hazard = Hazard.objects.get(pk=self.kwargs['pk'])
        user = self.request.user
        return user.has_perm('webapp.access_to_all_devices') or\
               hazard.site.pws in user.employee.pws.all() and user.has_perm('webapp.access_to_pws_devices')


class BPDeviceUpdateView(BPDeviceBaseFormView, UpdateView):
    permission = 'webapp.change_bpdevice'
    success_message = Messages.BPDevice.editing_success

    def get_context_data(self, **kwargs):
        context = super(BPDeviceUpdateView, self).get_context_data(**kwargs)
        hazard = context['form'].instance.hazard
        if self.allowed(hazard):
            context['hazard_pk'] = hazard.pk
            return context
        raise Http404

    def allowed(self, hazard):
        user = self.request.user
        return user.has_perm('webapp.access_to_all_devices') or\
               hazard.site.pws in user.employee.pws.all() and user.has_perm('webapp.access_to_pws_devices')

bigsurvey/webapp/views/helpers.py
class OperationNotAllowedInTrialPeriodException(Exception):
    pass

bigsurvey/webapp/templates/import/import.html
{% extends 'base.html' %}
{% load i18n widget_tweaks %}
{% block content %}
    <div class="wrapper">
        <div class="uk-grid">
            <div class="uk-width-1-2 uk-container-center">
                <form class="uk-form" method="post" enctype="multipart/form-data" name="import">
                    {% csrf_token %}

                    <div class="uk-form-row">
                        <p>{% trans 'Select File' %}</p>
                        {{ form.file.errors }}
                        {{ form.file }}
                    </div>
                    {% if form.pws %}
                        <div class="uk-form-row">
                            <p>{% trans 'Select PWS' %}</p>
                            {{ form.pws.errors }}
                            {{ form.pws }}
                        </div>
                    {% endif %}
                    <div class="uk-form-row">
                        <p>{% trans 'Select Date Format used in Excel file' %}</p>
                        {{ form.date_format.errors }}
                        {{ form.date_format }} <a href="#date-formats-help" data-uk-modal>{% trans 'Date Formats Help' %}</a>
                    </div>
                    <div class="uk-form-row hidden" data-content="date_format_other">
                        <p>{% trans 'If you do not find matching Date Format, provide it here manually' %}</p>
                        {{ form.date_format_other.errors }}
                        {{ form.date_format_other }}
                    </div>
                    <div class="uk-form-row">
                        <p>{% trans 'Check this if you want only to update or add new sites but not to deactivate missing ones' %}</p>
                        {{ form.update_only.errors }}
                        {{ form.update_only }}
                    </div>
                    <div class="uk-form-row">
                        <button type="submit" class="uk-button uk-button-primary">{% trans 'Submit' %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="uk-modal" id="date-formats-help">
        <div class="uk-modal-dialog">
            <a class="uk-modal-close uk-close uk-close-alt"></a>

            <p>{% trans 'Assume we have following date: September 3, 2013' %}</p>
            <table class="uk-table">
                <thead>
                <tr>
                    <th>{% trans 'Code' %}</th>
                    <th>{% trans 'Meaning' %}</th>
                    <th>{% trans 'Example' %}</th>
                </tr>
                </thead>
                <tbody>
                {% for dateformat in dateformat_help %}
                    <tr>
                        <td>{{ dateformat.code }}</td>
                        <td>{{ dateformat.meaning }}</td>
                        <td>{{ dateformat.example }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script>
        var dateFormatChanged = function (select) {
            if (select.val() == 'other') {
                $('[data-content="date_format_other"]').show();
            } else {
                $('[data-content="date_format_other"]').hide();
            }
        };

        $(document).ready(function () {
            dateFormatChanged($('select[name="date_format"]'));
            $('select[name="date_format"]').change(function () {
                dateFormatChanged($(this));
            });
        });
    </script>
{% endblock %}

bigsurvey/webapp/templates/import/import_log_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <div class="uk-grid">
        <div class="uk-width-1-1">
            {% include 'messages.html' %}
            <table class="uk-table uk-table-hover" id="import_logs">
                <thead>
                <tr class="border-bottom">
                    <th>{% trans "Datetime" %}</th>
                    <th>{% trans "User" %}</th>
                    <th>{% trans "PWS" %}</th>
                    <th>{% trans "Added sites" %}</th>
                    <th>{% trans "Updated sites" %}</th>
                    <th>{% trans "Deactivated sites" %}</th>
                    <th>{% trans "Duplicates file" %}</th>
                </tr>
                </thead>
                <tbody>
                {% for import_log in import_logs %}
                    <tr>
                        <td>{{ import_log.datetime }}</td>
                        <td>{{ import_log.user.get_full_name }}</td>
                        <td>{{ import_log.pws.number }}</td>
                        <td data-content="added_sites"><a href="{% url 'webapp:import_log_added_sites' import_log.pk %}">{{ import_log.added_sites.count }}</a></td>
                        <td data-content="updated_sites"><a href="{% url 'webapp:import_log_updated_sites' import_log.pk %}">{{ import_log.updated_sites.count }}</a></td>
                        <td data-content="deactivated_sites"><a href="{% url 'webapp:import_log_deactivated_sites' import_log.pk %}">{{ import_log.deactivated_sites.count }}</a></td>
                        <td>
                            {% if import_log.duplicates_file %}
                                <a href="{{ import_log.duplicates_file.url }}">{% trans "Download" %}</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>

            </table>
        </div>
    </div>
{% endblock %}

bigsurvey/webapp/templates/import/import_mappings.html
{% extends 'base.html' %}
{% load i18n form_helper staticfiles %}
{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/components/progress.min.css' %}">
{% endblock %}
{% block content %}
    <div class="wrapper">
        <div class="uk-grid">
            <div class="uk-width-1-1">
                <h2>{% trans 'Example rows' %}</h2>

                <div class="uk-overflow-container">
                    <table class="uk-table border-all example-rows-table uk-table-condensed">
                        <thead>
                        <tr>
                            {% for column_index, field_name in excel_field_headers %}
                                <th data-value="{{ column_index }}">
                                    {{ field_name }}
                                    <br>
                                    <span class="model_field uk-text-danger">{% trans 'None' %}</span>
                                </th>
                            {% endfor %}
                        </tr>
                        </thead>
                        <tbody>
                        {% for row in excel_example_rows %}
                            <tr>
                                {% for value in row %}
                                    <td>{{ value }}</td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="uk-grid">
            <div class="uk-width-2-3">
                {% if formset.non_form_errors %}
                    <div class="alert-margin-top uk-alert uk-alert-danger" data-uk-alert>
                        <a href="" class="uk-alert-close uk-close"></a>
                        {{ formset.non_form_errors }}
                    </div>
                {% endif %}
                <form class="uk-form" method="post" action="{% url 'webapp:import-mappings-process' %}" name="import-mappings">
                    <button type="submit" class="uk-button uk-button-primary" data-uk-modal="{target:'#excel-validation',bgclose:false,keyboard:false}">{% trans 'Submit' %}</button>
                    <button type="button" class="uk-button uk-button-danger" data-action="reset">{% trans 'Reset' %}</button>
                    {% if import_mappings %}
                        <button type="button" class="uk-button uk-button-success" data-action="populate">{% trans 'Populate choices from previous import' %}</button>
                    {% endif %}
                    {% csrf_token %}
                    {{ formset.management_form }}

                    <table class="uk-table border-none uk-table-condensed">
                        <tbody>
                        <tr>
                            <th class="uk-text-center">{% trans "Database Fields" %}</th>
                            <th class="uk-text-center">{% trans "Imported Fields" %}</th>
                            <th class="uk-text-center">{% trans "Database Fields" %}</th>
                            <th class="uk-text-center">{% trans "Imported Fields" %}</th>
                        </tr>
                        {% for row_index in rows_count|xrange_filter %}
                            <tr>
                                {% for col_index in '01'|make_list %}
                                    {% get_formset_index row_index col_index as index %}
                                    {% get_form_from_formset formset index as form %}
                                    <td>
                                        {{ form.model_field }}
                                        {% if form.fields.excel_field.required %}
                                            <span class="uk-text-bold uk-text-primary">
                                        {% endif %}
                                        {{ form.model_field.label }}
                                        {% if form.fields.excel_field.required %}
                                            </span>
                                        {% endif %}
                                        <br>
                                        <span class="uk-text-muted">{{ form.model_field.help_text }}</span>
                                    </td>
                                    <td>
                                        {{ form.excel_field }}
                                        {{ form.excel_field.errors }}
                                    </td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </form>
            </div>
            <div class="uk-width-1-3" style="padding-top: 20px;">
                <h3>{% trans 'Unselected Fields' %}</h3>
                <ul class="unselected-fields">
                    {% for value, field_name in excel_field_headers %}
                        <li data-value="{{ value }}">
                            {{ field_name }}
                        </li>
                    {% endfor %}
                </ul>
                <p class="uk-text-muted">
                    {% blocktrans %}
                        Note: Field, related to PWS (like "PWSID") may not be selected, because You have selected PWS in previous step.
                    {% endblocktrans %}
                </p>
            </div>
        </div>
    </div>
    <div id="excel-validation" class="uk-modal">
        <div class="uk-modal-dialog">
            <div class="uk-modal-spinner valign-center-modal-spinner spinner-crossbrowser"></div>
            <p class="uk-text-center uk-text-primary">{% trans 'Please wait while the file is being checked.' %}</p>
        </div>
    </div>
    <div id="import-progress" class="uk-modal">
        <div class="uk-modal-dialog">
            <div class="uk-modal-spinner valign-center-modal-spinner spinner-crossbrowser"></div>
            <p class="uk-text-center uk-text-primary">{% trans 'Import has started. You can see the progress below.' %}</p>

            <div class="uk-progress uk-progress-striped uk-active">
                <div class="uk-progress-bar" style="width: 0;">0%</div>
            </div>
        </div>
    </div>
    <div id="import-progress-modal-opener" class="uk-hidden" data-uk-modal="{target:'#import-progress',bgclose:false,keyboard:false}"></div>
{% endblock %}
{% block scripts %}
    <script>
        var none_text = '{% trans 'None' %}';
        var cached_mappings;
        {% if import_mappings %}
            cached_mappings = JSON.parse('{{ import_mappings|safe }}');
        {% else %}
            cached_mappings = null;
        {% endif %}

        {% if request.session.import_log_pk %}
            $(document).ready(function () {
                $('#import-progress-modal-opener').click();
                var url = '{% url 'webapp:import-progress' %}';
                setInterval(function () {
                    $.ajax(url, {
                        success: function (response) {
                            var percentage = response.progress + '%';
                            $('#import-progress').find('.uk-progress-bar').css('width', percentage).text(percentage);
                            if (response.progress == '100') {
                                window.location.href = "{% url 'webapp:import_log_list' %}";
                            }
                        }
                    })
                }, 5000);
            });
        {% endif %}
    </script>
    <script src="{% static 'js/custom/import.js' %}"></script>
{% endblock %}